# practise Numpy-pandas    Date:26 June 2020

In [13]:
 import numpy as np
 np.random.seed(0)
 def compute_reciprocals(values):
   output = np.empty(len(values))
   for i in range(len(values)):
     output[i] = 1.0 / values[i]
   return output
 values = np.random.random_integer(1, 10, size=5,replace=False)
 compute_reciprocals(values)

AttributeError: module 'numpy.random' has no attribute 'random_integer'

In [16]:
 import numpy as np
 np.random.seed(0)
 def compute_reciprocals(values):
   output = np.empty(len(values))
   for i in range(len(values)):
     output[i] = 1.0 / values[i]
   return output
 values = np.random.choice(range(1,20), size=5,replace=False)
 compute_reciprocals(values)

array([0.09090909, 0.5       , 0.11111111, 0.05263158, 0.06666667])

In [17]:
values


array([11,  2,  9, 19, 15])

In [18]:
print(1/values)

[0.09090909 0.5        0.11111111 0.05263158 0.06666667]


In [19]:
from scipy import special

In [21]:
special.gamma(5)

24.0

In [24]:
 big_array = np.random.rand(1000000)
 %timeit sum(big_array)


126 ms ± 3.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
x = np.random.randint(1,1000,size=1000000)
x

array([197,  46, 822, ..., 141, 536, 268])

In [33]:
np.max(x)

999

In [35]:
%timeit np.max(x)

527 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
%timeit max(x)

75.8 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
np.all(x)

True

In [10]:
values

array([6, 1, 4, 4, 8])

In [38]:
values

array([11,  2,  9, 19, 15])

# pandas starting

In [40]:
import pandas as pd

In [41]:
pd.__version__

'1.0.1'

In [42]:
pd.?

SyntaxError: invalid syntax (<ipython-input-42-9e1d5ce1a7ae>, line 1)

In [43]:
pd?

In [46]:
pd.<TAB>

SyntaxError: invalid syntax (<ipython-input-46-40b879790c84>, line 1)

In [45]:
pd.<abs>

SyntaxError: invalid syntax (<ipython-input-45-edf827541530>, line 1)

In [47]:
srs = pd.Series([2,3,4,5])

In [48]:
srs

0    2
1    3
2    4
3    5
dtype: int64

In [49]:
data.index

NameError: name 'data' is not defined

In [50]:
data.index()

NameError: name 'data' is not defined

In [51]:
srs.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
srs2=pd.Series([3,4,6,8])

In [53]:
srs2

0    3
1    4
2    6
3    8
dtype: int64

In [54]:
srs2.index

RangeIndex(start=0, stop=4, step=1)

In [57]:
dict={1:"yash",2:"deep",3:"aarzoo",4:"keval",5:"Naitik"}
indx=[range(2,5)]
srs=pd.Series(dict,index=indx)

In [58]:
indx

(2, 3, 4)    NaN
dtype: object

In [67]:
dict={1:"yash",2:"deep",3:"aarzoo",4:"keval",5:"Naitik"}
indx=[i for i in range(2,5)]
srs2=pd.Series(dict,index=[2,3,4])

In [68]:
srs3

NameError: name 'srs3' is not defined

In [69]:
srs2

2      deep
3    aarzoo
4     keval
dtype: object

In [65]:
indx

[2, 3, 4]

In [66]:
srs

2      deep
3    aarzoo
4     keval
dtype: object

In [60]:
srs

2      deep
3    aarzoo
4     keval
dtype: object

In [61]:
indx

[range(2, 5)]

In [83]:
roll={"yash":38,"aarzoo":36,"deep":22,"keval":16,"Naitik":19}
marks={"yash":100,"aarzoo":98,"deep":96,"keval":94}
rolls=pd.Series(roll)
marks=pd.Series(marks)
result=pd.DataFrame({"Roll":roll,"Mark":marks})

In [78]:
result

Roll   Mark
Naitik    19    NaN
aarzoo    36   98.0
deep      22   96.0
keval     16   94.0
yash      38  100.0

In [76]:
result

Roll  Mark
aarzoo    36    98
deep      22    96
keval     16    94
yash      38   100

In [72]:
result

Roll  Mark
aarzoo    36    98
deep      22    96
keval     16    94
yash      38   100

In [84]:
result[roll]

KeyError: "None of [Index(['yash', 'aarzoo', 'deep', 'keval', 'Naitik'], dtype='object')] are in the [columns]"

In [86]:
result["Roll"]

Naitik    19
aarzoo    36
deep      22
keval     16
yash      38
Name: Roll, dtype: int64

In [88]:
result["Mark"]

Naitik      NaN
aarzoo     98.0
deep       96.0
keval      94.0
yash      100.0
Name: Mark, dtype: float64

In [91]:
data=[{"a":i,"b":k+i}for i in range(10) for k in range(10)]

In [92]:
Df=pd.DataFrame(data)
Df

a   b
0   0   0
1   0   1
2   0   2
3   0   3
4   0   4
.. ..  ..
95  9  14
96  9  15
97  9  16
98  9  17
99  9  18

[100 rows x 2 columns]

In [94]:
pd.DataFrame([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}])

a  b
0  1  2
1  3  4

In [106]:
pd.DataFrame(np.random.rand(4,3),
columns=["a","b","c","d"],
index=["a","b","c"])

ValueError: Shape of passed values is (4, 3), indices imply (3, 4)

In [108]:
pd.DataFrame(np.random.rand(4,3),
columns=['asb','dfr','erge'],
index=['a','b','c','d'])

asb       dfr      erge
a  0.146300  0.554209  0.831968
b  0.376082  0.823946  0.959517
c  0.458861  0.793086  0.667593
d  0.457217  0.260481  0.417127

In [102]:
pd.DataFrame(np.random.rand(3, 2),
columns=['foo', 'bar'],
index=['a', 'b', 'c'])


foo       bar
a  0.438904  0.659886
b  0.031523  0.552914
c  0.629845  0.037592

In [110]:
ind=pd.Index([1,2,3,4,5])
pd.DataFrame(roll,index=ind)

yash  aarzoo  deep  keval  Naitik
1    38      36    22     16      19
2    38      36    22     16      19
3    38      36    22     16      19
4    38      36    22     16      19
5    38      36    22     16      19

In [111]:
result

Roll   Mark
Naitik    19    NaN
aarzoo    36   98.0
deep      22   96.0
keval     16   94.0
yash      38  100.0

In [112]:
result.pop

<bound method NDFrame.pop of         Roll   Mark
Naitik    19    NaN
aarzoo    36   98.0
deep      22   96.0
keval     16   94.0
yash      38  100.0>

In [113]:
result.pop()

TypeError: pop() missing 1 required positional argument: 'item'

In [114]:
result

Roll   Mark
Naitik    19    NaN
aarzoo    36   98.0
deep      22   96.0
keval     16   94.0
yash      38  100.0

In [117]:
result["multiple"]=result["Roll"]*result["Mark"]
result

Roll   Mark  multiple
Naitik    19    NaN       NaN
aarzoo    36   98.0    3528.0
deep      22   96.0    2112.0
keval     16   94.0    1504.0
yash      38  100.0    3800.0

In [118]:
result.T

Naitik  aarzoo    deep   keval    yash
Roll        19.0    36.0    22.0    16.0    38.0
Mark         NaN    98.0    96.0    94.0   100.0
multiple     NaN  3528.0  2112.0  1504.0  3800.0

In [119]:
result.values

array([[  19.,   nan,   nan],
       [  36.,   98., 3528.],
       [  22.,   96., 2112.],
       [  16.,   94., 1504.],
       [  38.,  100., 3800.]])

In [120]:
result.loc(result.Mark>95)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [124]:
result.loc[result.Mark>95,["Roll","Mark"]]

Roll   Mark
aarzoo    36   98.0
deep      22   96.0
yash      38  100.0

In [116]:
result

Roll   Mark  multiple
Naitik    19    NaN       NaN
aarzoo    36   98.0  0.367347
deep      22   96.0  0.229167
keval     16   94.0  0.170213
yash      38  100.0  0.380000

In [125]:
result.iloc[2,2]=1
result

Roll   Mark  multiple
Naitik    19    NaN       NaN
aarzoo    36   98.0    3528.0
deep      22   96.0       1.0
keval     16   94.0    1504.0
yash      38  100.0    3800.0